import type { AdvisorResult } from "../types.js";
import { courseColorCss } from "./colors.js";

export function renderHtml(result: AdvisorResult): string {
  const data = JSON.stringify(result).replace(/</g, "\\u003c");
  const colorEntries = [...new Set(result.strategies.flatMap((plan) => plan.sections.map((section) => section.code.trim().toUpperCase())))]
    .map((code) => [code, courseColorCss(code)]);
  const colors = JSON.stringify(Object.fromEntries(colorEntries));
  return `<!doctype html>
<html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>SUSTech Course Advisor</title><style>
:root{font-family:Inter,"PingFang SC",sans-serif;color:#17222b;background:#f4f6f8}body{margin:0}.shell{max-width:1280px;margin:auto;padding:18px}h1{margin:0 0 4px;font-size:22px}.muted{color:#64727d}.tabs{display:flex;gap:8px;margin:16px 0}.tabs button{border:1px solid #ccd5dc;background:white;padding:9px 14px;border-radius:999px;cursor:pointer}.tabs button.active{background:#173f5f;color:white}.summary{display:flex;flex-wrap:wrap;gap:10px;margin-bottom:14px}.pill{background:white;border-radius:10px;padding:9px 12px;box-shadow:0 2px 8px #0000000d}.principles{display:flex;flex-wrap:wrap;gap:8px;margin:0 0 14px;padding:0;list-style:none}.principles li{background:#e9eef0;color:#42545d;border-radius:999px;padding:6px 10px;font-size:12px}.grid{display:grid;grid-template-columns:72px repeat(7,1fr);background:white;border:1px solid #dbe2e7;border-radius:12px;overflow:hidden}.cell{min-height:72px;border-right:1px solid #e5eaee;border-bottom:1px solid #e5eaee;padding:5px;font-size:12px}.head{font-weight:700;text-align:center;min-height:auto;background:#eef3f6}.period{text-align:center;color:#64727d}.course{border-radius:7px;padding:6px;color:#10242e;cursor:pointer;min-height:52px;line-height:1.25;overflow-wrap:anywhere}.course .code{font-weight:800}.course .team{display:block;margin-top:4px;font-size:10px;color:#29414a}.details{margin-top:16px;background:white;padding:16px;border-radius:12px}.warning{color:#9a4b00}.source{font-size:12px;overflow-wrap:anywhere}@media(max-width:760px){.shell{padding:8px}.cell{font-size:9px;padding:2px;min-height:68px}.grid{grid-template-columns:38px repeat(7,minmax(92px,1fr));overflow-x:auto}.course{padding:4px}.course .team{font-size:8px}}@media print{.tabs{display:none}.shell{max-width:none}.details{break-before:page}}
</style></head><body><main class="shell"><h1>SUSTech Course Advisor</h1><div class="muted">${escapeHtml(result.semester)} · generated ${escapeHtml(result.generatedAt)}</div><nav class="tabs" id="tabs"></nav><section id="view"></section></main>
<script>const DATA=${data};const COURSE_COLORS=${colors};const labels={"high-load":"高负载","high-grading":"高给分","interest":"兴趣匹配"};let active=0;
function esc(v){return String(v??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]))}function colorFor(code){return COURSE_COLORS[String(code).trim().toUpperCase()]||'#dce6e8'}function render(){const p=DATA.strategies[active];tabs.innerHTML=DATA.strategies.map((x,i)=>'<button class="'+(i===active?'active':'')+'" onclick="active='+i+';render()">'+labels[x.strategy]+'</button>').join('');let cells='<div class="cell head">节次</div>'+['周一','周二','周三','周四','周五','周六','周日'].map(x=>'<div class="cell head">'+x+'</div>').join('');for(let period=1;period<=13;period++){cells+='<div class="cell period">'+period+'</div>';for(let day=1;day<=7;day++){const hits=p.sections.filter(s=>s.schedule.some(x=>x.day===day&&x.periodStart<=period&&x.periodEnd>=period));cells+='<div class="cell">'+hits.map(s=>'<div class="course" style="background:'+colorFor(s.code)+'" title="'+esc(s.teachers.join('、')||'教学团队待定')+'"><span class="code">'+esc(s.code)+'</span><br>'+esc(s.name)+'<span class="team">'+esc(s.teachers.join('、')||'教学团队待定')+'</span></div>').join('')+'</div>'}}const details=p.sections.map(s=>'<article><h3>'+esc(s.code)+' '+esc(s.name)+'</h3><div>教学团队：'+esc(s.teachers.join('、')||'待定')+' · '+s.credits+' 学分 · '+esc(s.campus)+'</div><p>'+((p.reasons[s.rwh]||[]).map(esc).join('<br>'))+'</p><div class="source">团队归因：'+esc(p.evidence[s.rwh]?.teamMatch||'none')+'；置信度 '+esc(p.evidence[s.rwh]?.confidence||0)+'</div></article>').join('');const main=p.mainProgramCredits??'—';const minor=p.minorProgramCredits??'—';const unresolved=p.unresolvedCredits??'—';view.innerHTML='<div class="summary"><div class="pill">排入学分 <strong>'+p.totalCredits+'</strong></div><div class="pill">主修确认 <strong>'+main+'</strong></div><div class="pill">辅修确认 <strong>'+minor+'</strong></div><div class="pill">归属未确认 <strong>'+unresolved+'</strong></div><div class="pill">课程数 <strong>'+p.sections.length+'</strong></div></div><ol class="principles"><li>① 必含与培养方案优先</li><li>② 主修与辅修学分分账</li><li>③ 不用未确认课程凑学分</li><li>④ 再比较完整团队给分与偏好</li></ol><div class="grid">'+cells+'</div>'+(p.warnings.length?'<p class="warning">'+p.warnings.map(esc).join('<br>')+'</p>':'')+'<section class="details">'+details+'</section>'}render();</script></body></html>`;
}

function escapeHtml(value: string): string {
  return value.replace(/[&<>\"]/g, (char) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", "\"": "&quot;" })[char]!);
}
