import type { AdvisorResult } from "../types.js";

export function renderHtml(result: AdvisorResult): string {
  const data = JSON.stringify(result).replace(/</g, "\\u003c");
  return `<!doctype html>
<html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>SUSTech Course Advisor</title><style>
:root{font-family:Inter,"PingFang SC",sans-serif;color:#17222b;background:#f4f6f8}body{margin:0}.shell{max-width:1200px;margin:auto;padding:24px}h1{margin:0 0 6px}.muted{color:#64727d}.tabs{display:flex;gap:8px;margin:20px 0}.tabs button{border:1px solid #ccd5dc;background:white;padding:9px 14px;border-radius:999px;cursor:pointer}.tabs button.active{background:#173f5f;color:white}.summary{display:flex;gap:12px;margin-bottom:16px}.pill{background:white;border-radius:10px;padding:10px 14px;box-shadow:0 2px 8px #0000000d}.grid{display:grid;grid-template-columns:72px repeat(7,1fr);background:white;border:1px solid #dbe2e7;border-radius:12px;overflow:hidden}.cell{min-height:48px;border-right:1px solid #e5eaee;border-bottom:1px solid #e5eaee;padding:5px;font-size:12px}.head{font-weight:700;text-align:center;min-height:auto;background:#eef3f6}.period{text-align:center;color:#64727d}.course{border-radius:7px;padding:5px;color:#10242e;cursor:pointer;min-height:34px}.details{margin-top:16px;background:white;padding:16px;border-radius:12px}.warning{color:#9a4b00}.source{font-size:12px;overflow-wrap:anywhere}@media(max-width:760px){.shell{padding:10px}.cell{font-size:10px;padding:2px}.grid{grid-template-columns:38px repeat(7,1fr)}}@media print{.tabs{display:none}.shell{max-width:none}.details{break-before:page}}
</style></head><body><main class="shell"><h1>SUSTech Course Advisor</h1><div class="muted">${escapeHtml(result.semester)} · generated ${escapeHtml(result.generatedAt)}</div><nav class="tabs" id="tabs"></nav><section id="view"></section></main>
<script>const DATA=${data};const labels={"high-load":"高负载","high-grading":"高给分","interest":"兴趣匹配"};const colors=['#b8e0d2','#ffd6a5','#bde0fe','#e4c1f9','#f7cad0','#cdeac0','#fff1a8'];let active=0;
function esc(v){return String(v??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]))}function render(){const p=DATA.strategies[active];tabs.innerHTML=DATA.strategies.map((x,i)=>'<button class="'+(i===active?'active':'')+'" onclick="active='+i+';render()">'+labels[x.strategy]+'</button>').join('');let cells='<div class="cell head">节次</div>'+['周一','周二','周三','周四','周五','周六','周日'].map(x=>'<div class="cell head">'+x+'</div>').join('');for(let period=1;period<=13;period++){cells+='<div class="cell period">'+period+'</div>';for(let day=1;day<=7;day++){const hits=p.sections.filter(s=>s.schedule.some(x=>x.day===day&&x.periodStart<=period&&x.periodEnd>=period));cells+='<div class="cell">'+hits.map((s,i)=>'<div class="course" style="background:'+colors[(p.sections.indexOf(s))%colors.length]+'" title="'+esc(s.teachers.join('、'))+'">'+esc(s.code)+'<br>'+esc(s.name)+'</div>').join('')+'</div>'}}const details=p.sections.map(s=>'<article><h3>'+esc(s.code)+' '+esc(s.name)+'</h3><div>'+esc(s.teachers.join('、')||'教师待定')+' · '+s.credits+' 学分 · '+esc(s.campus)+'</div><p>'+((p.reasons[s.rwh]||[]).map(esc).join('<br>'))+'</p><div class="source">团队归因：'+esc(p.evidence[s.rwh]?.teamMatch||'none')+'；置信度 '+esc(p.evidence[s.rwh]?.confidence||0)+'</div></article>').join('');view.innerHTML='<div class="summary"><div class="pill">总学分 <strong>'+p.totalCredits+'</strong></div><div class="pill">课程数 <strong>'+p.sections.length+'</strong></div></div><div class="grid">'+cells+'</div>'+(p.warnings.length?'<p class="warning">'+p.warnings.map(esc).join('<br>')+'</p>':'')+'<section class="details">'+details+'</section>'}render();</script></body></html>`;
}

function escapeHtml(value: string): string {
  return value.replace(/[&<>\"]/g, (char) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", "\"": "&quot;" })[char]!);
}
